library(nlstools)
data("L.minor")
str(L.minor)
plot(L.minor$conc,L.minor$rate, xlab="concentraci??n del sustrato (mmol^-3)", ylab ="Tasa de consumo (peso/h")
mod1 = nls(rate~Vm*conc/(k+conc), data=L.minor, start=list(k=20, Vm=120), trace=TRUE) 
summary(mod1)
deviance(mod1)
logLik(mod1)
coef(mod1)
concVal <- with(L.minor, seq(min(conc),+ max(conc), length.out=10))
predict(mod1, data.frame(conc = concVal))
plot(rate~conc,data=L.minor, ylim = c(10,130), ylab = "Tasa de consumo", xlab = Concentracion~sustrato~(mmol~m^-3))
concVal <- with(L.minor, seq(min(conc),max(conc), length.out = 100))
lines(concVal, predict(mod1, newdata = data.frame(conc= concVal)))
abline(h = coef(mod1)[2], lty=2)
